

services:
  db:
    image: mysql:8.0
    container_name: mysql-db-for-order-system
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: OderManagement
      MYSQL_DATABASE: order_management_db
      MYSQL_USER: springuser
      MYSQL_PASSWORD: springpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

volumes:
  db_data: